// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form': string;
  'select': string;
  'text': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
