// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'info': string;
  'logo': string;
  'logoText': string;
  'logoTriangle': string;
  'logoTriangleReverse': string;
  'main': string;
}
export const cssExports: CssExports
export default cssExports
