// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ButtonStyle': string;
  'CheckStyle': string;
  'FormItem': string;
  'InputStyle': string;
  'logo': string;
  'signIn': string;
}
export const cssExports: CssExports;
export default cssExports;
