// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card-container': string;
  'management': string;
  'tabs': string;
}
export const cssExports: CssExports;
export default cssExports;
