// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'articleAnchor': string;
  'articleAnchorLink': string;
  'articleBread': string;
  'articleContent': string;
  'articleContentH1': string;
  'articleContentH2': string;
  'articleInfo': string;
  'articleLayout': string;
  'articleLeft': string;
  'articleRight': string;
  'articleTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
